const Joi = require('joi');
const ResourceController = require('./mainController');

const createFileHeaderSchema = Joi.object({
   file_id: Joi.number().required(),
   testtoolconfiguration_testtoolname: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_testtoolversionstring: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_projectname: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_logfileencoding: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_pythonversion: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_testfile: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_logfilepath: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_logfilemode: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_ctrlfilepath: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_configfile: Joi.string().allow('').allow(null).default(null),
   testtoolconfiguration_confname: Joi.string().allow('').allow(null).default(null),
   testfileheader_author: Joi.string().allow('').allow(null).default(null),
   testfileheader_project: Joi.string().allow('').allow(null).default(null),
   testfileheader_testfiledate: Joi.string().allow('').allow(null).default(null),
   testfileheader_version_major: Joi.string().allow('').allow(null).default(null),
   testfileheader_version_minor: Joi.string().allow('').allow(null).default(null),
   testfileheader_version_patch: Joi.string().allow('').allow(null).default(null),
   testfileheader_keyword: Joi.string().allow('').allow(null).default(null),
   testfileheader_shortdescription: Joi.string().allow('').allow(null).default(null),
   testexecution_useraccount: Joi.string().allow('').allow(null).default(null),
   testexecution_computername: Joi.string().allow('').allow(null).default(null),
   testrequirements_documentmanagement: Joi.string().allow('').allow(null).default(null),
   testrequirements_testenvironment: Joi.string().allow('').allow(null).default(null),
   testbenchconfig_name: Joi.string().allow('').allow(null).default(null),
   testbenchconfig_data: Joi.string().allow('').allow(null).default(null),
   preprocessor_parameters: Joi.string().allow('').allow(null).default(null),
   preprocessor_filter: Joi.string().allow('').allow(null).default(null)
})
const updateFileHeaderSchema = Joi.object({
   testtoolconfiguration_testtoolname: Joi.string(),
   testtoolconfiguration_testtoolversionstring: Joi.string(),
   testtoolconfiguration_projectname: Joi.string(),
   testtoolconfiguration_logfileencoding: Joi.string(),
   testtoolconfiguration_pythonversion: Joi.string(),
   testtoolconfiguration_testfile: Joi.string(),
   testtoolconfiguration_logfilepath: Joi.string(),
   testtoolconfiguration_logfilemode: Joi.string(),
   testtoolconfiguration_ctrlfilepath: Joi.string(),
   testtoolconfiguration_configfile: Joi.string(),
   testtoolconfiguration_confname: Joi.string(),
   testfileheader_author: Joi.string(),
   testfileheader_project: Joi.string(),
   testfileheader_testfiledate: Joi.string(),
   testfileheader_version_major: Joi.string(),
   testfileheader_version_minor: Joi.string(),
   testfileheader_version_patch: Joi.string(),
   testfileheader_keyword: Joi.string(),
   testfileheader_shortdescription: Joi.string(),
   testexecution_useraccount: Joi.string(),
   testexecution_computername: Joi.string(),
   testrequirements_documentmanagement: Joi.string(),
   testrequirements_testenvironment: Joi.string(),
   testbenchconfig_name: Joi.string(),
   testbenchconfig_data: Joi.string(),
   preprocessor_parameters: Joi.string(),
   preprocessor_filter: Joi.string()
})

module.exports = new ResourceController("file header", 
                                         "tbl_file_header", 
                                         "file_id", 
                                         createFileHeaderSchema, 
                                         updateFileHeaderSchema)